### ISSUE TITLE
[Question] Session timeout increase?

### ISSUE THREAD

**Issue by OdinVex** [MeCJay12/lsi-storage-authority#1]
First and foremost, thank you for this Docker, it's awesome. Question though, is it possible to increase the session timeout? It's sooo short... I'd prefer a 15-30 minute timeout. (Edit: If possible, even hackishly, I can hijack the entrypoint to adjust any file I need.)

**Comment by MeCJay12** [comment]
Re-open this or submit a pull if you happen to find something. I'm more than happy to merge it in and support it.
